# [[redirects]]
#   from = "/2022/01/14/how-to-write-ux-ui-design-principles"
#   to = "/blog/how-to-write-ux-ui-design-principles"
#   status = 301

# [[redirects]]
#   from = "/2021/11/22/yave-ux-design-case-study"
#   to = "/blog/yave-ux-design-case-study"
#   status = 301

# [[redirects]]
#   from = "/2021/11/19/ux-is-more-important-than-ui"
#   to = "/blog/ux-is-more-important-than-ui"
#   status = 301

# [[redirects]]
#   from = "/2021/11/19/how-to-be-a-great-ux-ui-designer"
#   to = "/blog/how-to-be-a-great-ux-ui-designer"
#   status = 301

# [[redirects]]
#   from = "/2021/11/19/handle-changing-ux-ui-design-requirements"
#   to = "/blog/handle-changing-ux-ui-design-requirements"
#   status = 301

# [[redirects]]
#   from = "/2021/11/18/perfect-ui-is-pointless-without-great-ux"
#   to = "/blog/perfect-ui-is-pointless-without-great-ux"
#   status = 301

# [[redirects]]
#   from = "/2021/11/18/how-to-write-ux-design-brief"
#   to = "/blog/how-to-write-ux-design-brief"
#   status = 301

# [[redirects]]
#   from = "/2021/11/18/how-to-stop-defending-and-start-presenting-your-work"
#   to = "/blog/how-to-stop-defending-and-start-presenting-your-work"
#   status = 301

# [[redirects]]
#   from = "/2021/11/18/forget-what-you-know-about-being-a-great-designer"
#   to = "/blog/forget-what-you-know-about-being-a-great-designer"
#   status = 301

# [[redirects]]
#   from = "/2021/08/12/ux-ui-design-risks"
#   to = "/blog/ux-ui-design-risks"
#   status = 301

# [[redirects]]
#   from = "/2021/08/12/4-fallacies-of-great-design"
#   to = "/blog/4-fallacies-of-great-design"
#   status = 301

# [[redirects]]
#   from = "/2021/06/03/everyones-favorite-ux-ui-designer"
#   to = "/blog/everyones-favorite-ux-ui-designer"
#   status = 301

# [[redirects]]
#   from = "/2021/06/02/how-to-design-confidently-without-ever-being-the-expert"
#   to = "/blog/how-to-design-confidently-without-ever-being-the-expert"
#   status = 301

# [[redirects]]
#   from = "/2021/05/07/build-an-app-without-a-ux-designer"
#   to = "/blog/build-an-app-without-a-ux-designer"
#   status = 301

# [[redirects]]
#   from = "/2021/05/06/how-to-design-without-a-designer"
#   to = "/blog/how-to-design-without-a-designer"
#   status = 301

# [[redirects]]
#   from = "/2021/05/04/is-ux-research-worth-it"
#   to = "/blog/is-ux-research-worth-it"
#   status = 301

# [[redirects]]
#   from = "/2021/05/03/how-to-overcome-8-common-objections-to-ux-research"
#   to = "/blog/how-to-overcome-8-common-objections-to-ux-research"
#   status = 301

# [[redirects]]
#   from = "/projects/null"
#   to = "/projects"
#   status = 301